#!/usr/bin/python3

import requests, json, subprocess, sys, os, datetime, pwd, urllib.parse

# Set stuff up
url = 'https://discordapp.com/api/webhooks/761765537381351444/0N65QqVbqprslWQDE4VNFh3f1jmVSATJP8ml2yhw-BIXR8F8oA48BKkGqpxBgzMipYQM'
n = int(open('/home/pi/failedlogins', 'r').read())
headers = {'content-type': 'application/json'}
message = {}
message['embeds'] = [{}]
message['embeds'][0]['color'] = 0

# Increment our main counter
n += 1
with open('/home/pi/failedlogins', 'w') as f:
    f.write(str(n))

# Get the relevant line of the auth log
logline = ''
log = subprocess.Popen(['tail', '-n', '20', '/var/log/auth.log'], stdout=subprocess.PIPE)
for i in range(50):
    line = str(log.stdout.readline())
    if 'Failed password' in line:
        #print(line)
        logline = line

#print('logline: ' + logline)

# Get our data
service = os.environ['PAM_SERVICE']
ip = os.environ['PAM_RHOST']
username = os.environ['PAM_USER']
password = input()[:-1]

# Generate the message
message['embeds'][0]['description'] = '**Service:** {service}\n**Source:** {ip}\n**Username:** {username}\n**Password:** {password}'.format(service=service, ip=ip, username=username, password=password)
message['embeds'][0]['title'] = 'Total attempts: ' + str(n)
message['embeds'][0]['timestamp'] = datetime.datetime.now().isoformat()

# Send the message
reply = requests.post(url, json.dumps(message), headers=headers)

# Send to visualizer
requests.get('http://localhost/attempt/' + urllib.parse.quote(ip) + '/' + urllib.parse.quote(username) + '/' + urllib.parse.quote(password))

# Check if user exists, create if not
try:
    pwd.getpwnam(username)
except KeyError:
    subprocess.Popen(['/bin/addhoneypot', username])

print(reply)
print(reply.content)
